/**
 * soundbank.js – KaiOS sample‑based soundbank engine.
 *
 * Loads SoundFonts and plays them, optionally LAYERED (several banks
 * selected at once → all their samples ring together on the same note).
 * Two sources are supported:
 *   • raw SoundFont files  (.sf2 / .sf3)      → parsed in‑app by SfParser
 *   • .soundbank.json banks (generated by tools/sfextract.js) — legacy route
 *
 * MULTI‑BANK model (Settings → Synth → Load Soundfont):
 *   banks[]  each holds its own decoded noteMap. A bank is "active" while
 *            selected==true; play() renders every selected bank.
 *   The loaded‑font REGISTRY (paths + selection) is persisted in
 *   localStorage — i.e. in the APP's own storage, never written to the
 *   internal/SD partitions — so a reboot re-reads the same files and
 *   restores the exact set + selection (restore()).
 *
 * Public API:
 *   Soundbank.loadFromFile(name, path, volName, ArrayBuffer)  // SF2/SF3 → new bank
 *   Soundbank.addBank(bankMeta, noteMap)                      // low‑level add
 *   Soundbank.removeBank(id) / Soundbank.toggleSelect(id)
 *   Soundbank.setSelected(id, bool) / Soundbank.moveBank(from, to)
 *   Soundbank.getBanks()                  // [{id,name,path,selected,presetCount,…}]
 *   Soundbank.load(url)                   // legacy .soundbank.json
 *   Soundbank.play(note, velocity, delaySec, durSec)
 *   Soundbank.unload()                    // free buffers + registry
 *   Soundbank.restore()                   // reload persisted registry (boot)
 *   Soundbank.isReady()
 */
var Soundbank = (function () {
  'use strict';

  var REGISTRY_KEY = 'pfa.soundfonts';
  var UID_KEY = 'pfa.soundfonts.uid';

  var ctx = null;          // AudioContext shared with Synth
  var banks = [];          // [{id, name, path, volName, selected, presetCount, noteMap}]

  /** Initialise AudioContext (or reuse existing one from Synth) */
  function ensureContext() {
    if (ctx) return ctx;
    if (window.AudioContext) ctx = new AudioContext('content');
    else if (window.webkitAudioContext) ctx = new webkitAudioContext('content');
    else throw new Error('Web Audio API not available');
    return ctx;
  }

  function nextId() {
    var n = 1;
    try { n = parseInt(localStorage.getItem(UID_KEY) || '1', 10) || 1; } catch (e) {}
    var id = Date.now().toString(36) + '-' + n;
    try { localStorage.setItem(UID_KEY, String(n + 1)); } catch (e) {}
    return id;
  }

  // ── Registry persistence (app storage only — never a partition) ──
  function persist() {
    try {
      var list = banks.map(function (b) {
        return {
          id: b.id,
          name: b.name,
          path: b.path,
          volName: b.volName,
          selected: !!b.selected,
          sourceType: b.sourceType
        };
      });
      localStorage.setItem(REGISTRY_KEY, JSON.stringify(list));
    } catch (e) {
      console.warn('[Soundbank] registry persist failed', e);
    }
  }
  function readRegistry() {
    try {
      var raw = localStorage.getItem(REGISTRY_KEY);
      var arr = raw ? JSON.parse(raw) : [];
      return Array.isArray(arr) ? arr : [];
    } catch (e) { return []; }
  }

  // ── AudioBuffer decoding ──

  /** decodeAudioData() tolerant of both promise AND callback Agora. */
  function decodeBuffer(ab) {
    return new Promise(function (resolve, reject) {
      var c = ensureContext();
      if (typeof c.decodeAudioData === 'function') {
        try {
          var r = c.decodeAudioData(ab);
          if (r && typeof r.then === 'function') {
            r.then(resolve, reject);
            return;
          }
        } catch (e) {}
        // Callback form (Gecko 48 / some KaiOS builds).
        try {
          c.decodeAudioData(ab, function (buf) { resolve(buf); }, function () { reject(new Error('decodeAudioData failed')); });
          return;
        } catch (e2) { reject(e2); return; }
      }
      reject(new Error('decodeAudioData unavailable'));
    });
  }

  /** Build the {note → [entries]} map for one parsed font. */
  function buildNoteMap(parsed, bufBySample) {
    var noteMap = {};
    var presets = parsed.presets || [];
    for (var p = 0; p < presets.length; p++) {
      var preset = presets[p];
      var zones = preset.zones || [];
      for (var z = 0; z < zones.length; z++) {
        var zone = zones[z];
        var sample = (parsed.samples && parsed.samples[zone.sampleIndex]) || null;
        if (!sample) continue;
        var buffer = bufBySample[zone.sampleIndex];
        if (!buffer) continue;
        var rootKey = (zone.rootKey != null) ? zone.rootKey
                   : (sample.originalKey != null ? sample.originalKey : 60);
        for (var n = zone.keyLo; n <= zone.keyHi; n++) {
          if (n < 0 || n > 127) continue;
          if (!noteMap[n]) noteMap[n] = [];
          // Skip an exact duplicate layer (same sample on the same root).
          var dup = false;
          for (var e = 0; e < noteMap[n].length; e++) {
            if (noteMap[n][e].buffer === buffer && noteMap[n][e].rootKey === rootKey) { dup = true; break; }
          }
          if (!dup) noteMap[n].push({ buffer: buffer, rootKey: rootKey, sampleRate: sample.sampleRate });
        }
      }
    }
    return noteMap;
  }

  /**
   * Decode every distinct sample of a parsed font into an AudioBuffer.
   * Sequential on purpose: SF2 files can hold dozens of samples and KaiOS
   * decodes in‑place — decoding one at a time bounds peak memory.
   * SF3 Ogg samples are Fed straight to decodeAudioData (Gecko decodes
   * Ogg/Vorbis natively when the bytes are a full stream).
   */
  function decodeSamples(parsed) {
    return new Promise(function (resolve, reject) {
      var samples = parsed.samples || [];
      var out = {};
      var idx = 0;
      (function next() {
        if (idx >= samples.length) { resolve(out); return; }
        var smp = samples[idx];
        var bufBytes;
        if (smp.ogg && smp.pcm) {
          // Raw Ogg stream (SF3) — give it to the decoder as-is.
          bufBytes = smp.pcm.buffer;
        } else {
          // PCM16 mono → wrap into a WAV container first.
          bufBytes = SfParser.pcm16ToWav(smp.pcm, smp.sampleRate);
        }
        decodeBuffer(bufBytes).then(function (abuf) {
          out[idx] = abuf;
          idx++; next();
        }, function () {
          // One bad sample must not kill the whole bank — skip it.
          console.warn('[Soundbank] sample decode failed: ' + smp.name);
          idx++; next();
        });
      })();
    });
  }

  // ── Bank lifecycle ──

  /**
   * Parse + decode + add a SoundFont FILE as a new bank.
   * name/path/volName come from the scanner entry (or picker).
   */
  function loadFromFile(name, path, volName, arrayBuffer) {
    return new Promise(function (resolve, reject) {
      var parsed;
      try { parsed = SfParser.parse(arrayBuffer); }
      catch (e) { reject(e); return; }
      if (!parsed.presets || !parsed.presets.length) {
        reject(new Error('SoundFont contains no presets'));
        return;
      }
      decodeSamples(parsed).then(function (bufBySample) {
        var noteMap = buildNoteMap(parsed, bufBySample);
        var bank = addBank({
          id: nextId(),
          name: name || parsed.name || path.split('/').pop() || 'SoundFont',
          path: path || '',
          volName: volName || '',
          selected: true,
          sourceType: 'file',
          presetCount: parsed.presets.length
        }, noteMap);
        resolve(bank);
      }, reject);
    });
  }

  /**
   * Legacy .soundbank.json route — fetch the JSON, decode its base64 WAV(s)
   * and register it as a single bank spanning the full note range.
   */
  async function load(url) {
    const resp = await fetch(url);
    if (!resp.ok) throw new Error('Failed to fetch soundbank: ' + resp.status);
    const data = await resp.json();
    const presets = data.presets || [];
    const preset = presets[0];
    if (!preset) throw new Error('Soundbank JSON contains no presets');
    const zone = (preset.zones && preset.zones[0]) || null;
    if (!zone) throw new Error('No zone data in first preset');

    const wavBase64 = zone.wav;
    const binary = atob(wavBase64);
    const wavArray = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) wavArray[i] = binary.charCodeAt(i);
    const audioBuf = await decodeBuffer(wavArray.buffer);

    const noteMap = {};
    const rootKey = zone.rootKey || 60;
    const sampleRate = zone.sampleRate || (audioBuf ? audioBuf.sampleRate : 44100);
    for (let n = 0; n < 128; n++) {
      noteMap[n] = [{ buffer: audioBuf, rootKey: rootKey, sampleRate: sampleRate }];
    }
    addBank({
      id: nextId(),
      name: preset.name || 'Soundbank',
      path: url || '',
      volName: '',
      selected: true,
      sourceType: 'json',
      presetCount: presets.length
    }, noteMap);
    console.log('[Soundbank] JSON bank loaded, ready for playback');
  }

  /** Low‑level: register a fully decoded bank object + its noteMap. */
  function addBank(meta, noteMap) {
    var bank = {
      id: meta.id || nextId(),
      name: meta.name || 'Bank',
      path: meta.path || '',
      volName: meta.volName || '',
      selected: meta.selected !== false,
      sourceType: meta.sourceType || 'file',
      presetCount: meta.presetCount || 0,
      noteMap: noteMap || {}
    };
    banks.push(bank);
    persist();
    return bank;
  }

  function removeBank(id) {
    for (var i = 0; i < banks.length; i++) {
      if (banks[i].id === id) {
        banks.splice(i, 1);
        persist();
        return true;
      }
    }
    return false;
  }

  function toggleSelect(id) {
    var b = bankById(id);
    if (b) { b.selected = !b.selected; persist(); return b.selected; }
    return null;
  }
  function setSelected(id, sel) {
    var b = bankById(id);
    if (b) { b.selected = !!sel; persist(); return b.selected; }
    return null;
  }

  /** Reorder rows in the Settings list (move mode: ▲▼ reorder). */
  function moveBank(fromIdx, toIdx) {
    if (fromIdx < 0 || fromIdx >= banks.length) return false;
    toIdx = Math.max(0, Math.min(banks.length - 1, toIdx));
    if (fromIdx === toIdx) return true;
    var b = banks.splice(fromIdx, 1)[0];
    banks.splice(toIdx, 0, b);
    persist();
    return true;
  }

  function bankById(id) {
    for (var i = 0; i < banks.length; i++) if (banks[i].id === id) return banks[i];
    return null;
  }

  function getBanks() {
    return banks.map(function (b) {
      return {
        id: b.id,
        name: b.name,
        path: b.path,
        volName: b.volName,
        selected: !!b.selected,
        sourceType: b.sourceType,
        presetCount: b.presetCount
      };
    });
  }

  /** A bank is usable for playback when it has at least one mapped note. */
  function anySelected() {
    for (var i = 0; i < banks.length; i++) {
      if (banks[i].selected && Object.keys(banks[i].noteMap).length) return true;
    }
    return false;
  }
  function isReady() { return anySelected(); }

  /**
   * Play a note on EVERY selected bank (layering). delaySec/durSec are in
   * seconds relative to AudioContext.currentTime.
   */
  function play(note, velocity, delaySec, durSec) {
    if (!anySelected()) return;
    var audioCtx = ensureContext();
    if (audioCtx.state !== 'running') {
      try { if (audioCtx.resume) audioCtx.resume(); } catch (e) {}
    }
    var gainVal = Math.max(0, Math.min(1, velocity / 127));
    var startTime = audioCtx.currentTime + (delaySec || 0);

    for (var bi = 0; bi < banks.length; bi++) {
      var bank = banks[bi];
      if (!bank.selected) continue;
      var entries = bank.noteMap[note];
      if (!entries || !entries.length) continue;
      for (var ei = 0; ei < entries.length; ei++) {
        var entry = entries[ei];
        if (!entry || !entry.buffer) continue;
        try {
          var source = audioCtx.createBufferSource();
          source.buffer = entry.buffer;
          var gainNode = audioCtx.createGain();
          gainNode.gain.value = gainVal;
          source.connect(gainNode).connect(audioCtx.destination);
          var stopTime = startTime + (durSec || entry.buffer.duration);
          source.start(startTime);
          source.stop(stopTime);
        } catch (e) { /* one bad layer must never stop the rest */ }
      }
    }
  }

  function unload() {
    banks = [];
    try { localStorage.removeItem(REGISTRY_KEY); } catch (e) {}
    if (ctx && typeof ctx.close === 'function') ctx.close();
    ctx = null;
  }

  /**
   * Reload the persisted registry on boot: each entry's file is re-read
   * from its stored volume+path and re-parsed, and its selected state is
   * reapplied. Missing/corrupt files are skipped (stale registry entries do
   * not block the rest).
   */
  function restore() {
    return new Promise(function (resolve) {
      var entries = readRegistry();
      if (!entries.length) { resolve(0); return; }
      var done = 0;
      (function next() {
        if (done >= entries.length) { resolve(entries.length); return; }
        var item = entries[done];
        done++;
        if (!item || !item.path) { next(); return; }
        if (typeof SfScan === 'undefined' || !SfScan.readByPath) { next(); return; }
        SfScan.readByPath(item.volName, item.path).then(function (ab) {
          return loadFromFile(item.name || item.path.split('/').pop(),
                              item.path, item.volName, ab);
        }).then(function (bank) {
          try { setSelected(bank.id, item.selected !== false); } catch (e) {}
          next();
        }, function () {
          console.warn('[Soundbank] restore skipped: ' + item.path);
          next();
        });
      })();
    });
  }

  return {
    loadFromFile: loadFromFile,
    addBank: addBank,
    removeBank: removeBank,
    toggleSelect: toggleSelect,
    setSelected: setSelected,
    moveBank: moveBank,
    getBanks: getBanks,
    load: load,
    play: play,
    unload: unload,
    restore: restore,
    isReady: isReady
  };
})();