/**
 * soundbank.js – KaiOS soundbank engine.
 * Loads a .soundbank.json (generated by tools/sfextract.js) and provides
 * a simple sample‑based playback API that can replace the oscillator synth.
 *
 * Public API:
 *   Soundbank.load(url)               // fetch JSON, decode base64 WAVs, create AudioBuffers
 *   Soundbank.play(note, velocity, delaySec, durSec)
 *   Soundbank.unload()                // free buffers
 */

var Soundbank = (function () {
  'use strict';

  var ctx = null;               // AudioContext shared with Synth
  var presets = [];             // array of preset objects from JSON
  var noteMap = {};             // note (0-127) -> { buffer, rootKey, sampleRate }
  var isReady = false;

  /** Initialise AudioContext (or reuse existing one from Synth) */
  function ensureContext() {
    if (ctx) return ctx;
    if (window.AudioContext) ctx = new AudioContext();
    else if (window.webkitAudioContext) ctx = new webkitAudioContext();
    else throw new Error('Web Audio API not available');
    return ctx;
  }

  /** Load .soundbank.json from a URL and prepare buffers. */
  async function load(url) {
    const resp = await fetch(url);
    if (!resp.ok) throw new Error('Failed to fetch soundbank: ' + resp.status);
    const data = await resp.json();
    presets = data.presets || [];

    // Build mapping of note ranges to buffers (first preset used for simplicity)
    const preset = presets[0]; // fallback to first
    if (!preset) throw new Error('Soundbank JSON contains no presets');

    const zone = (preset.zones && preset.zones[0]) || null;
    if (!zone) throw new Error('No zone data in first preset');

    const wavBase64 = zone.wav;
    const wavArray = Uint8Array.from(atob(wavBase64), c => c.charCodeAt(0));
    const audioCtx = ensureContext();
    const audioBuf = await audioCtx.decodeAudioData(wavArray.buffer);

    // Fill noteMap for the whole 0‑27 range using the same buffer.
    for (let n = 0; n < 128; n++) {
      noteMap[n] = {
        buffer: audioBuf,
        rootKey: zone.rootKey || 60,
        sampleRate: zone.sampleRate || audioCtx.sampleRate,
      };
    }
    isReady = true;
    console.log('[Soundbank] loaded, ready for playback');
  }

  /** Play a note using the pre‑decoded AudioBuffer.
   *  delaySec and durSec are in seconds relative to AudioContext.currentTime.
   */
  function play(note, velocity, delaySec, durSec) {
    if (!isReady) return; // silently ignore if no bank
    const entry = noteMap[note];
    if (!entry) return;
    const audioCtx = ensureContext();
    const source = audioCtx.createBufferSource();
    source.buffer = entry.buffer;
    // Apply velocity as gain (0‑115 => 0.0‑1.0)
    const gainNode = audioCtx.createGain();
    const gainVal = Math.max(0, Math.min(1, velocity / 127));
    gainNode.gain.value = gainVal;
    source.connect(gainNode).connect(audioCtx.destination);
    const startTime = audioCtx.currentTime + (delaySec || 0);
    const stopTime = startTime + (durSec || entry.buffer.duration);
    source.start(startTime);
    source.stop(stopTime);
  }

  function unload() {
    // Drop references so GC can reclaim buffers.
    noteMap = {};
    presets = [];
    isReady = false;
    if (ctx && typeof ctx.close === 'function') ctx.close();
    ctx = null;
  }

  return {
    load: load,
    play: play,
    unload: unload,
    isReady: function () { return isReady; },
  };
})();